services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USER=restill_user
      - DATABASE_PASSWORD=restill_password
      - DATABASE_NAME=restill_db

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=restill_user
      - POSTGRES_PASSWORD=restill_password
      - POSTGRES_DB=restill_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: